package src

WINDOW_WIDTH :: 800.0
WINDOW_HEIGHT :: 600.0
WINDOW_TITLE :: "Breakout"
TARGET_FPS :: 60
PLAYER_SPEED :: 5

PLAYER_POSITION_Y :: WINDOW_HEIGHT - 100

PLAYER_WIDTH :: 100
PLAYER_HEIGHT :: 30